;;; -*- lexical-binding: t -*-

(ert-deftest internal-domain ()
  (-each '(("https://jira.com"      . "jira.com")
           ("http://jira.com"       . "jira.com")
           ("jira.com"              . "jira.com")
           ("https://jira.com/abc"  . "jira.com")
           ("http://jira.com/a/b/c" . "jira.com")
           ("jira.com.org/"         . "jira.com.org"))
    (lambda (x)
      (-let (((url . ans) x))
        (let ((jira-base-url url))
          (should (equal (jira--domain) ans)))))))

(ert-deftest internal-at ()
  (-each '( ("key" (("key" . "value")) "value")
            (("key") (("key" . "value")) "value")
            (("b") (("a" . "1") ("b" . "2")) "2")
            (("b" "c") (("a" . "1") ("b" . (("c" . "3")))) "3")
            (1 [1 2 3] 2)
            (("a" 1) (("a" . [1 2 3])) 2))
    (lambda (x)
      (-let (((path obj ans) x))
        (should (equal (jira--at path obj) ans))))))

(ert-deftest internal-rest-url ()
  (let ((jira-base-url "https://jira.com"))
    (should (equal (jira--rest-url "issues") "https://jira.com/rest/api/latest/issues")))
  (let ((jira-base-url "https://jira.com/"))
    (should (equal (jira--rest-url "issues") "https://jira.com/rest/api/latest/issues")))
  (let ((jira-base-url "https://jira.com/a/b/c"))
    (should (equal (jira--rest-url "issues") "https://jira.com/rest/api/latest/issues"))))
