;;; -*- lexical-binding: t -*-

(ert-deftest internal-domain ()
  (-each '(("https://jira.com"      . "jira.com")
           ("http://jira.com"       . "jira.com")
           ("jira.com"              . "jira.com")
           ("https://jira.com/abc"  . "jira.com")
           ("http://jira.com/a/b/c" . "jira.com")
           ("jira.com.org/"         . "jira.com.org"))
    (lambda (x)
      (-let (((url . ans) x))
        (let ((jiraffe-base-url url))
          (should (equal (jiraffe--domain) ans)))))))

(ert-deftest internal-at ()
  (-each '( ("key" (("key" . "value")) "value")
            (("key") (("key" . "value")) "value")
            (("b") (("a" . "1") ("b" . "2")) "2")
            (("b" "c") (("a" . "1") ("b" . (("c" . "3")))) "3")
            (1 [1 2 3] 2)
            (("a" 1) (("a" . [1 2 3])) 2))
    (lambda (x)
      (-let (((path obj ans) x))
        (should (equal (jiraffe--at path obj) ans))))))

(ert-deftest internal-rest-url ()
  (let ((jiraffe-base-url "https://jira.com"))
    (should (equal (jiraffe--rest-url "issues") "https://jira.com/rest/api/latest/issues")))
  (let ((jiraffe-base-url "https://jira.com/"))
    (should (equal (jiraffe--rest-url "issues") "https://jira.com/rest/api/latest/issues")))
  (let ((jiraffe-base-url "https://jira.com/a/b/c"))
    (should (equal (jiraffe--rest-url "issues") "https://jira.com/rest/api/latest/issues"))))

(ert-deftest internal-issue-key-from-text ()
  (--each '( ("CT-123"   . "CT-123")
             ("CT-123  " . "CT-123")
             ("https://bugreports.qt.io/browse/QTJIRA-40" . "QTJIRA-40")
             ("bugreports.qt.io/browse/QTJIRA-40" . "QTJIRA-40")
             ("Hello World" . ()) )
    (let ((in  (car it))
          (out (cdr it)))
      (should (equal (jiraffe--issue-key-from-text in) out)))))
